describe('My First Test', () => {
  it('Ordering a delivery from Dominos.', () => {
    cy.visit('https://www.dominos.com/en/restaurants')
    cy.get("#Delivery").click();
    cy.get("#Type").select("Apartment")
    cy.get("#label-LocationName").type("Bolsa Row Apartments")
    cy.get("#Street").type("15100 Brookhurst Street")
    cy.get("#UnitNumber").type("10")
    cy.get("#PostalCode").type("92683")
    // cy.get("#City").type("Westminster")
    // cy.get("#Region").select("CA")
    cy.get(".css-14js2j3").eq(0).click()
    // cy.get("#entree-Pizza").click()
    cy.get(".c-order-entrees-specialtypizza").click()
    cy.get('[data-dpz-track-evt-name="Order CTA | Memphis BBQ Chicken"]').click()
    cy.get('[data-dpz-track-evt-name="Customize CTA | Pacific Veggie"]').click()
    cy.get('[data-quid="pizza-size-16"]').click()
    cy.get('[data-quid="bubble-code-overlay-close"]').click()
    cy.get(".pizza-topping__weight").eq(0).select("Extra")
    cy.get("#sauce-topping-Bq").click()
    cy.get(".pizza-topping__weight").eq(1).select("Extra")
    cy.get('[aria-label="Bacon"]').click()
    cy.get('[aria-label="Pepperoni"]').click()
    cy.get('[aria-label="Premium Chicken"]').click()
    cy.get('[aria-label="increase Ranch count"]').click()
    cy.get('[aria-label="increase Marinara Dipping Sauce count"]').click()
    cy.get(".single-page-pizza-builder-desktop__quantity").click()
    cy.get('[name="quantity"]').select("2")
    cy.get(".single-page-pizza-builder-desktop__add-to-order").click()
    cy.get("#js-myOrderPage").click()
    cy.get(".js-closeButton").click()
    cy.get(".submitButton.qa-OrCheck").click()
    cy.get(".sam-continue--button__confirmation").click()
  })
})


